$(function(){
    $('#btnHome').click(function(){
        $('#divHome').hide();
    });
    $('#btnInfo').click(function(){
        $('#divInfo').hide();
    });
    $('#btnContato').click(function(){
        $('#divContato').hide();
    });
    $('#btnShow').click(function(){
        $('div').show();
    });
})